### ISSUE TITLE
0.0.91 delete not working (mac)

### ISSUE THREAD

**Issue by kadorito** [BobStrogg/teslacam-browser#21]
Hi, awesome app I will donate !

on the latest version, the delete buttons (folder and individial level) do not delete anything (although the confirmation scrrens pops up and no error message comes).
I'm running it against the USB key, and deleting directly froim MAcoOS works.

**Comment by BobStrogg** [comment]
Thanks for the feedback!  This’ll be fixed in next update 👍🏻

**Comment by fmonera** [comment]
Delete still not working on 0.094 (Linux):

Uncaught Exception:
Error: ENOENT: no such file or directory, rmdir 'SavedClips/2019-05-30_12-38-26'
at Object.rmdirSync (fs.js:677:3)
at deleteFolder ... main.js:205:6
at EventEmitter.ipcMain.on ... main.js:265:52
...

I suppose you need to add the full path of the directory to delete.

**Comment by elitest** [comment]
I'm also having this issue on Windows deleting off a file share(mapped to a drive later).

**Comment by alanhogan** [comment]
I cloned the repo, ran `npm i && npm run start`, and am getting this error as well. OS X 10.14.5 (18F132)

**Comment by fmonera** [comment]
Delete is fixed in 0.0.94.8.
It has an unexpected behavior but I will open a new issue.
